### ISSUE TITLE
curl_setopt(): supplied resource is not a valid cURL handle resource

### ISSUE THREAD

**Issue by maxakropolis** [nvanheuverzwijn/monolog-logdna#1]
We began to experience this error when attempting to upgrade from PHP7.0 to PHP7.1 
```
ERROR: Uncaught CLI exception {"exception":"[object] (ErrorException(code: 2): 
curl_setopt(): supplied resource is not a valid cURL handle resource at 
vendor/nvanheuverzwijn/monolog-logdna/src/Monolog/Handler/LogdnaHandler.php:89)
```
It seems that line 89 needs the `$closeAfterDone` parameter passing, otherwise Monolog destroys the curl resource that is initialised in `LogdnaHandler`

https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/Curl/Util.php#L32

I'm unsure why this worked previously but doesn't work now, but I forked the code to prove this and it works.

**Comment by nvanheuverzwijn** [comment]
I will look into this, thanks for the issue !

**Comment by PLaRoche** [comment]
Same issue here

**Comment by nvanheuverzwijn** [comment]
@PLaRoche Thanks for the PR. @maxakropolis See version `2.0.1` and `1.0.2`. Sorry for the delay, thank you for your time.

Cheers !

**Comment by maxakropolis** [comment]
Cheers @PLaRoche @nvanheuverzwijn
