### ISSUE TITLE
Compatibility with php 8.1

### ISSUE THREAD

**Issue by ekomurz** [nvanheuverzwijn/monolog-logdna#10]
Recent documentations says that version 2 is for php 7.4 and 8.1. 
However: the composer.json for 2.2.x requires only php 7.4.

Can you change this?

**Comment by nvanheuverzwijn** [comment]
@ekomurz Fixed in v2.2.2. Thanks!

**Comment by nvanheuverzwijn** [comment]
@ekomurz Feel free to open the issue again if it doesn't work.
