### ISSUE TITLE
LogdnaHandler `write` declaration incompatible with AbstractProcessingHandler class

### ISSUE THREAD

**Issue by mdscarlos** [nvanheuverzwijn/monolog-logdna#6]
Hi there,

I'm facing this issue while trying to use the monolog-logdna lib, because of it's declaration of `write` function, that is incompatible with the declaration inside AbstractProcessingHandler class wich is extended, just like this:

LogDnaHandler -> write declaration:
`protected function write(array $record)`

AbstractProcessingHandler -> write declaration:
`abstract protected function write(array $record): void`

The error message I get from exception: `Declaration of Zwijn\\Monolog\\Handler\\LogdnaHandler::write(array $record) must be compatible with Monolog\\Handler\\AbstractProcessingHandler::write(array $record): void`

I guess it needs the `:void` return declaration type, my Laravel version is `^6.2` and the LogDnaHandler is `^2.1`.

Thank you in advance 😄

**Comment by mdscarlos** [comment]
I saw there is already a pull request to fix it -> https://github.com/nvanheuverzwijn/monolog-logdna/pull/5

**Comment by dr-matt-smith** [comment]
not sure how active this project is
here is link to my fork with fixes (I've made pull request too)

[https://github.com/dr-matt-smith/monolog-logdna](https://github.com/dr-matt-smith/monolog-logdna)
