### ISSUE TITLE
Release v3.1.0 on packagist.org

### ISSUE THREAD

**Issue by Jhnbrn90** [nvanheuverzwijn/monolog-logdna#9]
Dear @nvanheuverzwijn,

Thanks for merging my PR #8. I'd like to use the newly released version 3.1.0 in my PHP project. 
To be able to install the new version using composer, the new version must be available on Packagist.org.
I see that the changes are not automatically synced and requires a manual push from your side. 

Would you please be so kind to push the new version to Packagist? 
Thanks in advance!

Best, 

John

**Comment by nvanheuverzwijn** [comment]
Hey @Jhnbrn90 ,

I will definitely take a look!

Thanks

**Comment by nvanheuverzwijn** [comment]
@Jhnbrn90 Alright, it's done! Let me know if there's any other issues!

Thank you!

**Comment by Jhnbrn90** [comment]
@nvanheuverzwijn Thank you! 👍 😄
